trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

parameters:
- name: environment
  displayName: 'Select Environment'
  type: string
  values:
    - prod
    - testing
    - dev
  default: 'dev'

- name: notificationEmail
  displayName: 'Notification Email'
  type: string
  default: ''  # Default to an empty string

- name: slackWebhookUrl
  displayName: 'Slack Webhook URL'
  type: string
  default: ''  # Default to an empty string

stages:
- stage: Build
  displayName: 'Build Application'
  condition: always()  # Prevents the stage from being rerun
  jobs:
  - job: DotNetBuild
    displayName: 'Run dotnet build command'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    
    # Assign a value to an output variable using Bash
    - bash: |
        selectedEnvironment=$(echo $(environment))
        echo "##vso[task.setvariable variable=SelectedEnvironment;isOutput=true]$selectedEnvironment"
      displayName: 'Set Output Variable'

- stage: Deploy
  displayName: 'Deploy Application'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy .NET application'
    environment: 'YourEnvironmentName'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deployment is progressing to environment $(SelectedEnvironment)"
            displayName: 'Run shell script'

- stage: Notification
  displayName: 'Notification'
  dependsOn: Deploy
  jobs:
  - job: SendNotification
    displayName: 'Send Deployment Notification'
    steps:
    # Check if notificationEmail is not empty and send email if specified
    - bash: |
        if [[ -n "$(notificationEmail)" ]]; then
          echo "Sending email to $(notificationEmail)"
          # Include email sending logic here
        fi
      displayName: 'Send Email Notification'
    
    # Check if slackWebhookUrl is not empty and send Slack notification if specified
    - bash: |
        if [[ -n "$(slackWebhookUrl)" ]]; then
          echo "Sending Slack notification to $(slackWebhookUrl)"
          # Include Slack notification logic here
        fi
      displayName: 'Send Slack Notification'
