# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: DotNetBuild
    displayName: 'Run dotnet build command'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - powershell: |
        $selectedEnvironment = Read-Host "Select environment (e.g., prod, testing, dev)"
        Write-Host "Selected environment: $selectedEnvironment"
        echo "##vso[task.setvariable variable=SelectedEnvironment;isOutput=true]$selectedEnvironment"
      displayName: 'Select Environment'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $selectedEnvironment = "$(SelectedEnvironment)"
          if ($selectedEnvironment -eq "prod") {
            # Add deployment tasks for the production environment
          }
          elseif ($selectedEnvironment -eq "testing") {
            # Add deployment tasks for the testing environment
          }
          elseif ($selectedEnvironment -eq "dev") {
            # Add deployment tasks for the development environment
          }
          else {
            Write-Host "Invalid environment selected: $selectedEnvironment"
            exit 1
          }
      displayName: 'Select Deployment Tasks'
- stage: Deploy
  displayName: 'Deploy Application'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy .net application'
    environment: 'YourEnvironmentName'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deployment is progressing"
            displayName: 'Run shell script'